// Mocks generated by Mockito 5.4.6 from annotations
// in pos_coffee_shop/test/providers/payment_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_coffee_shop/models/order_model.dart' as _i6;
import 'package:pos_coffee_shop/models/payment_model.dart' as _i4;
import 'package:pos_coffee_shop/services/order_service.dart' as _i5;
import 'package:pos_coffee_shop/services/payment_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i2.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> processPayment(_i4.Payment? payment) =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, [payment]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getCustomerName(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerName, [orderId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i5.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.OrderList>> getOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, []),
            returnValue: _i3.Stream<List<_i6.OrderList>>.empty(),
          )
          as _i3.Stream<List<_i6.OrderList>>);

  @override
  _i3.Future<List<Map<String, dynamic>>?> getItemsOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsOrder, [orderId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i3.Future<List<Map<String, dynamic>>?>);
}
