// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW3qzsnntqsqp8tkBi0TsDYNn0s5SNuNc',
    appId: '1:635270097970:web:019c634439eee42d7f602b',
    messagingSenderId: '635270097970',
    projectId: 'pos-coffee-shop-ab302',
    authDomain: 'pos-coffee-shop-ab302.firebaseapp.com',
    storageBucket: 'pos-coffee-shop-ab302.firebasestorage.app',
    measurementId: 'G-R1FLVBF1PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gCjVCRSJ9xBNToYrEU4T50jwjf4Lx38',
    appId: '1:635270097970:android:0f9df5dc0139d2a97f602b',
    messagingSenderId: '635270097970',
    projectId: 'pos-coffee-shop-ab302',
    storageBucket: 'pos-coffee-shop-ab302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hikIKDDhk5DHKen0uJ8C4Vt4NmP_CPA',
    appId: '1:635270097970:ios:2eea700f070d57ee7f602b',
    messagingSenderId: '635270097970',
    projectId: 'pos-coffee-shop-ab302',
    storageBucket: 'pos-coffee-shop-ab302.firebasestorage.app',
    iosClientId: '635270097970-pleperjq51go1q5rme9kvthgm2mt2a5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.posCoffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hikIKDDhk5DHKen0uJ8C4Vt4NmP_CPA',
    appId: '1:635270097970:ios:2eea700f070d57ee7f602b',
    messagingSenderId: '635270097970',
    projectId: 'pos-coffee-shop-ab302',
    storageBucket: 'pos-coffee-shop-ab302.firebasestorage.app',
    iosClientId: '635270097970-pleperjq51go1q5rme9kvthgm2mt2a5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.posCoffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW3qzsnntqsqp8tkBi0TsDYNn0s5SNuNc',
    appId: '1:635270097970:web:78966a3e1fe0d9817f602b',
    messagingSenderId: '635270097970',
    projectId: 'pos-coffee-shop-ab302',
    authDomain: 'pos-coffee-shop-ab302.firebaseapp.com',
    storageBucket: 'pos-coffee-shop-ab302.firebasestorage.app',
    measurementId: 'G-PR65GLLG7X',
  );

}